- name: Variables preference
  hosts: web
  vars_files:
  - variables.yaml
  # vars_prompt:
  # - name : PERSON 
  #   prompt: "Please Enter Your Name "
  #   private: false
  # - name : WISHES
  #   prompt: "please Enter your wishes "
  #   private: false
  # vars:
  #   PERSON: "ARUN FROM PLAY"
  #   WISHES: "GOOD MORNING FROM PLAY"
  tasks:
  - name: variables defining
    # vars:
    #   PERSON: "ARUN FROM TASK"
    #   WISHES: "MORNING FROM TASK"
    ansible.builtin.debug:
      msg: Hi {{PERSON}} GOOD {{WISHES}}


#CMD
#TASK
#FILES
#PROMPT
#PLAY
#INVENTORY
