- name: conditions
  hosts: web
  tasks:
  - name: check roboshop user exists are not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  
  - name: print output value
    ansible.builtin.debug:
      msg: "Vallue is {{output}}"