- name: conditions
  hosts: web
  tasks:
  - name: check roboshop user exists are not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  
  - name: print output value
    ansible.builtin.debug:
      msg: "output value is: {{output}}"

  - name: status is 
    ansible.builtin.debug:
      msg: "status is : {{output.rc}}"
  
  - name: Create user
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0