- name: Loops in ansible
  hosts: web
  become: yes
  tasks:
  - name: Loop 
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - nginx
    - ansible
    - postfix